##***EJERCICIOS NUMPY*** 
**Sebastian Belalcazar Mosquera - Grupo 185**

In [ ]:
#Que es una matriz: cuadricula de valores del mismo tipo y se encuentra indexada por una tupla de enteros positivos.
import numpy as np

matriz = np.array([[1, 2, 3, 4,], [5, 6, 7, 8]])

print(matriz)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#Que es vector: una zona de almacenamiento que contiene una serie de elementos del mismo tipo, osea los elementos de la matriz.
import numpy as np 

matriz = np.array([[1, 3 ],[2,5]])
matrizinv = np.linalg.inv(matriz)

print(matriz)
print(matrizinv)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [91]:
#Que es una matriz inversa: La matriz inversa de una matriz es igual a la matriz adjunta de su matriz traspuesta,dividida por su determinante, siempre que este no sea cero.
import numpy as np

matriz = np.array([[1, 3],[2,5]])
matrizinv = np.linalg.inv(matriz)

print(matriz)
print(matrizinv)

[[1 3]
 [2 5]]
[[-5.  3.]
 [ 2. -1.]]


In [ ]:
#Se invirtio una matriz con el metodo linalg.inv. 
import numpy as np

matriz = np.array([[2, 7, 1, 3],[5, 8, 1, 4],[3, 7, 5, 1], [4, 9, 2, 7]])
metodlinalg = np.linalg.inv(matriz)

print(matriz)
print(metodlinalg)

[[2 7 1 3]
 [5 8 1 4]
 [3 7 5 1]
 [4 9 2 7]]
[[-0.3968254   0.38888889  0.02380952 -0.05555556]
 [ 0.36507937 -0.02777778 -0.01190476 -0.13888889]
 [-0.23809524 -0.16666667  0.21428571  0.16666667]
 [-0.17460317 -0.13888889 -0.05952381  0.30555556]]


In [147]:
#Que hace el metodo shape en Numpy: Practicamente nos permite saber cuantas columnas y cuantas filas tiene una matriz.
import numpy as np

matriz = np.array([[1, 2, 3, 4,], [5, 6, 7, 8]])
metodshape = np.shape(matriz)

print(matriz)
print(metodshape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [ ]:
#Crear un vector del rango 80 a 150
import numpy as np

vector = np.array(range(80,151))

print(vector)

[ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115
 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133
 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150]


In [ ]:
#Invertir el vector a con el metodo flip en Numpy
import numpy as np

a= np.array([12,45,67,89])
ainv = np.flip(a)

print(ainv)

[89 67 45 12]


In [ ]:
#Crear una matriz 3x3 con valores de 0 a 8
import numpy as np

matriz = np.array([[0,1,2], [3,4,5], [6,7,8]])

print(matriz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [69]:
#Crear una matriz 10x10 con solo unos, luego cambiar la ultima fila por 10 sus elementos
import numpy as np

matriz = np.zeros([10,10])
 
for i in range(10):
    for j in range(10):
        matriz[i,j] = 1
        if i == 9:
          matriz[i,j] = j+1

print(matriz)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]]


In [68]:
#cree una matriz 5x5 con valores aleatorios, buscar el método random de Numpy y utilizarlos, luego mostrar de la ultima fila solo las dos últimas columnas de estas.
import numpy as np

matriz = np.random.randint(100, size=(5, 5))

print(matriz[4])
print(matriz[4][3])
print(matriz[4][4])

[59 83 57 61 71]
61
71


In [148]:
#Dada la siguiente matriz 𝑛𝑝.𝑎𝑟𝑎𝑛𝑔𝑒(1,101).𝑟𝑒𝑠ℎ𝑎𝑝𝑒(10,10) / 100 - Hallar la suma de todos sus elementos y el promedio.
import numpy as np

matriz = np.arange(1,101).reshape(10,10)/100

elem = 0
suma = 0

for fila in matriz:
    for elemento in fila:
        suma += elemento
        elem += 1

promedio = suma / elem
print(matriz)
print(f"La suma es {suma} y el promedio es {promedio},la matriz que tiene {elem} elementos")

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]
La suma es 50.5 y el promedio es 0.505,la matriz que tiene 100 elementos


In [95]:
#Investigar el método linspace en Numpy: genera un array que tiene una similitud al rango que inicia en 0, finaliza en 1 y generara 20 valores que seran valores entre ese rango especificado
#En pocas palabras recorre desde 0 a 1 generando 20 numeros que estan en ese rango
import numpy as np

matriz = np.linspace(0,1,20)

print(matriz)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [146]:
#La siguiente instrucción me permite crear una matriz 5x5 utilizando un rango entre 1 y 26, sin incluir el 26
import numpy as np

mat = np.arange(1,26).reshape(5,5)
salida = np.sum(mat, axis=-1)

print("Matriz")
print(mat)
print(f"Primera Fila = {mat[0]}")
print(f"Penultimo dato de la primera fila = {mat[0][3]}")
print(f"Ultimo dato de la primera fila = {mat[0][4]}")
print(f"La segunda columna = {mat[:, 1]}")
print(f"La primera columna = {mat[:, 0]}")
print(f"La ultima columna = {mat[:, 4]}")
print(f"La primera fila = {mat[0]}")
print("El promedio es: ", int(np.mean(mat)))
print(f"la suma de la ultima columna es: {salida}")
print(f"El elemento en la posicion (5,2): {mat[4][1]}")

Matriz
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Primera Fila = [1 2 3 4 5]
Penultimo dato de la primera fila = 4
Ultimo dato de la primera fila = 5
La segunda columna = [ 2  7 12 17 22]
La primera columna = [ 1  6 11 16 21]
La ultima columna = [ 5 10 15 20 25]
La primera fila = [1 2 3 4 5]
El promedio es:  13
la suma de la ultima columna es: [ 15  40  65  90 115]
El elemento en la posicion (5,2): 22
